import AvgAeneas.Extracted.Avg
import AvgFast.Proofs

/-!
# The Rust `avg` is the average

`Avg.Rust.avg` (in `AvgAeneas/Extracted/`) is generated by Aeneas from `rust/src/lib.rs`;
never edit it by hand.
In Aeneas's model, `u64 + u64` returns `fail` on overflow (Rust panics), so the
correctness theorem has two parts: the call never panics, and its result is `avgSpec`.
-/

open Aeneas Aeneas.Std Result

namespace Avg

/-- The Rust function never panics, and returns exactly `avgSpec`. -/
theorem rust_avg_spec (a b : U64) :
    Rust.avg a b ⦃ r => r.bv = avgSpec a.bv b.bv ⦄ := by
  unfold Rust.avg
  step as ⟨i, _, hi⟩
  step as ⟨i1, _, hi1⟩
  step as ⟨i2, _, hi2⟩
  step with U64.add_bv_spec as ⟨r, _, hr⟩
  · -- no overflow on `+`
    simp only [← UScalar.bv_toNat, hi, hi1, hi2]
    exact (avgFast_noOverflow a.bv b.bv).trans_eq (by simp [U64.max, U64.numBits, UScalarTy.numBits])
  · -- value
    simp only [hr, hi, hi1, hi2]
    exact avgFast_eq_spec a.bv b.bv

/-- End to end, in plain arithmetic: `avg a b` returns `⌊(a + b) / 2⌋`, with no panic. -/
theorem rust_avg_correct (a b : U64) :
    ∃ r, Rust.avg a b = ok r ∧ r.val = (a.val + b.val) / 2 := by
  obtain ⟨r, h, hr⟩ := (WP.spec_equiv_exists _ _).mp (rust_avg_spec a b)
  refine ⟨r, h, ?_⟩
  have := congrArg BitVec.toNat hr
  simp only [UScalar.bv_toNat] at this
  rw [this, avgSpec_toNat, UScalar.bv_toNat, UScalar.bv_toNat]

end Avg
