import AvgAeneas.Impl.Avg
import AvgAlgo.Proofs

/-!
# The Rust `avg` is the average

## Main results (these statements, plus `IsAvg`, are what a reviewer must read)

* `rust_avg_correct`: for all `a b : u64`, `avg a b` returns (never panics) some `r`
  with `IsAvg a b r`.
* `rust_avg_toNat`: the same, as `r = ⌊(a + b) / 2⌋`.

`Avg.Rust.avg` (in `AvgAeneas/Impl/`) is generated by Aeneas from `impl/rust/src/lib.rs`;
never edit it by hand. In Aeneas's model, `u64 + u64` returns `fail` on overflow (Rust
panics), so "returns `ok r`" is the no-panic guarantee. Aeneas models `avg` as a pure
function, so there is no other state to preserve.
-/

open Aeneas Aeneas.Std Result

namespace Avg

/-- The Rust function never panics, and returns `avgFast` of its inputs. -/
theorem rust_avg_spec (a b : U64) :
    Rust.avg a b ⦃ r => r.bv = avgFast a.bv b.bv ⦄ := by
  unfold Rust.avg
  step as ⟨i, _, hi⟩
  step as ⟨i1, _, hi1⟩
  step as ⟨i2, _, hi2⟩
  step with U64.add_bv_spec as ⟨r, _, hr⟩
  · -- no overflow on `+`
    simp only [← UScalar.bv_toNat, hi, hi1, hi2]
    exact (avgFast_noOverflow a.bv b.bv).trans_eq (by simp [U64.max, U64.numBits, UScalarTy.numBits])
  · -- value
    simp only [hr, hi, hi1, hi2]
    rfl

/-- **Main theorem.** `avg a b` never panics, and its result is the floor average
(`IsAvg`, from the trusted spec). -/
theorem rust_avg_correct (a b : U64) :
    ∃ r, Rust.avg a b = ok r ∧ IsAvg a.bv b.bv r.bv := by
  obtain ⟨r, h, hr⟩ := (WP.spec_equiv_exists _ _).mp (rust_avg_spec a b)
  exact ⟨r, h, hr ▸ avgFast_isAvg a.bv b.bv⟩

/-- Plain-arithmetic form: `avg a b` returns `⌊(a + b) / 2⌋`. -/
theorem rust_avg_toNat (a b : U64) :
    ∃ r, Rust.avg a b = ok r ∧ r.val = (a.val + b.val) / 2 := by
  obtain ⟨r, h, hr⟩ := rust_avg_correct a b
  refine ⟨r, h, ?_⟩
  have : r.bv.toNat = (a.bv.toNat + b.bv.toNat) / 2 := hr
  simpa only [UScalar.bv_toNat] using this

end Avg
