-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [avg]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace Avg.Rust

/-- [avg::avg]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def avg (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← lift (a &&& b)
  let i1 ← lift (a ^^^ b)
  let i2 ← i1 >>> 1#i32
  i + i2

end Avg.Rust
